name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Build
      run: xcodebuild clean build -project 'EssentialFeed/EssentialFeed.xcodeproj' -scheme "EssentialFeed" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    - name: Run tests
      run: xcodebuild clean build test -project 'EssentialFeed/EssentialFeed.xcodeproj' -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
